backend:
  name: git-gateway
  branch: master
local_backend: true
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
i18n: 
  structure: multiple_files
  locales: [en, ko]
  default_locale: en
collections:
  - name: blog
    label: Blog
    folder: content
    create: true
    i18n: true
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    format: toml-frontmatter
    fields:
      - label: Draft
        name: draft
        widget: boolean
        i18n: true
        default: true 
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Description
        name: description
        widget: string
        i18n: true
      - label: Publish Date
        name: date
        widget: datetime
        i18n: duplicate
      - label: Taxonomies
        name: taxonomies
        widget: object
        summary: "tags: {{fields.tags}}, categories: {{fields.categories}}"
        i18n: true
        fields:
          - label: Tags
            name: tags
            widget: list
            i18n: true
          - label: Categories
            name: categories
            widget: list
            i18n: true # FIXME change it to duplicate when Netlify CMS supports it
      - label: Body
        name: body
        widget: markdown
        i18n: true